name: Test End-to-End

on: [push]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installation de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Installation des dépendances
        run: npm install

      - name: Démarrage du serveur de développement avec http-server
        run: npx http-server ./src -p 8080 &

      - name: Attente du serveur et vérification de index.html
        run: |
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/index.html)
          if [ "$STATUS_CODE" -eq 200 ]; then
            echo "Serveur démarré et index.html accessible (code 200)"
          else
            echo "Erreur: index.html non accessible (code $STATUS_CODE)"
            exit 1
          fi

      - name: Changer les permissions de l'exécutable TestCafe
        run: chmod +x ./node_modules/.bin/testcafe

      - name: Exécution des tests TestCafe
        uses: DevExpress/testcafe-action@latest
        with:
          args: |
            cd test
            npx testcafe chrome:headless e2e.test.js --reporter spec --base-url http://localhost:8080
            
      - name: Arrêt du serveur de développement
        if: always()
        run: pkill -f "http-server"